project:
  type: website
  output-dir: docs

website:
  title: "White Box Autonomy"
  navbar:
    collapse: true
    collapse-below: xl
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "First-hand Reports"
        href: firsthand.qmd
      - text: "Community Reports"
        href: otherusers.qmd
      - text: "Acknowledgements"
        href: acknowledgements.qmd
 
  page-footer:
    center: |
      <div class="social-footer">
        <a href="https://www.youtube.com/@WhiteBoxAutonomy" target="_blank">
          <img src="images/youtube.svg" class="footer-icon" alt="YouTube">
        </a>
        <a href="https://x.com/WhiteBoxAV" target="_blank">
          <img src="images/X.svg" class="footer-icon x-icon" alt="X">
        </a>
      </div>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

