project:
  type: website
  output-dir: docs

website:
  title: "White Box Autonomy"
  navbar:
    collapse: true
    collapse-below: xl
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "First-hand Reports"
        href: firsthand.qmd
      - text: "Community Reports"
        href: otherusers.qmd
      - text: "Acknowledgements"
        href: acknowledgements.qmd
      
    right:
      - href: https://www.youtube.com/@WhiteBoxAutonomy
        text: "![](images/youtube.svg)"
      - href: https://x.com/WhiteBoxAV
        text: "![](images/x.svg)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

