---
title: "Community Reports"
format: html
---

### Waymo freezes on Active Train Tracks.

**Event**: A driverless Waymo Jaguar I-Pace in Austin stopped between active train tracks and a lowered crossing gate, narrowly avoiding collision with a passing CapMetro train, as captured in a 25-second video showing the white vehicle inches from the rails. \
**Country**: USA.\   
**Date**: 09 March, 2026.\
**Outcome**: near miss.\
[**Video link: X post**](https://x.com/ABC/status/2031558071630123088)\
**Contributor**: ABC News.

### Waymo Blocks Ambulance.

**Event**: A Waymo autonomous vehicle obstructs an ambulance and police cars en route to a March 1, 2026, mass shooting at Buford's Backyard Beer Garden in Austin, Texas, where 3 people were killed and 14 injured by a gunman suspected in a terrorism probe. \
**Country**: USA.\   
**Date**: 02 March, 2026.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/Breaking911/status/2028160742755537397)\
**Contributor**: Breaking911.

### Tesla FSD crash in snowy conditions.

**Event**: a Tesla on Full Self-Driving (FSD) colliding with a sliding pickup truck on a snowy highway. FSD attempted to slow and evade but ultimately braced for impact.\
**Country**: Canada.\   
**Date**: Unknown, but the video clip was posted on March 14, 2026.\
**Outcome**: Collision.\
[**Video link: X post**](https://x.com/paulctan/status/2032942478894985277)  \
**Contributor**: Paul C Tan.

### Tesla FSD in heavy fog.

**Event**: In heavy fog and wet conditions, Tesla FSD does not adjust its driving behavior (e.g., slowing down) to account for reduced visibility and traction. While it may still operate safely, it shows no clear awareness of the risk, making it feel unreliable and difficult to trust in these conditions.\
**Country**: Unknown.\   
**Date**: Unknown, but the video clip was posted on March 17, 2026.\
**Outcome**: safe.\
[**Video link: X post**](https://x.com/mikepat711/status/2033552410308690410)  \
**Contributor**: Mike P.

### Tesla FSD seriously speeding.

**Event**: Tesla FSD was set to Chill mode but was driving at 44% above the posted speed limit.\
**Country**: Unknown.\   
**Date**: Unknown, but the video clip was posted on March 16, 2026.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/AIDRIVR/status/2033353203518169463)  \
**Contributor**: ΛI DRIVR.

### Tesla FSD Navigates Wrecked Bus Off-Road

**Event**: a Tesla on Full Self-Driving (FSD) navigates around a massive wrecked tour bus, handling the situation impressively by going fully off-road across rough, bumpy grass.\
**Country**: Probably Thailand.\   
**Date**: Unknown, but the video clip was posted on March 15, 2026.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/drewinnovations/status/2033056567247921461)  \
**Contributor**: drewinnovations.

### Cybertruck crash into a concrete barrier.

**Event**: A Houston driver was in a Cybertruck in August 2025 when the Autopilot-controlled vehicle drove straight into a concrete barrier on a Y-shaped overpass on 69 Eastex Freeway. The vehicle was expected to follow a curve to the right, but when it failed to do so, she disengaged the driver-assistance feature. Still, “it was too late” once she took control of the wheel and the vehicle crashed into the barrier, the lawsuit claims.\
**Country**: USA.\   
**Date**: August, 2025.\
**Outcome**: Collision.\
[**Video link: X post**](https://x.com/statesman/status/2030055934316163225)  \
**Contributor**: Austin Statesman.

### Waymo driving into oncoming traffic.

**Event**: Waymo drives into oncoming traffic in Austin, TX, and Finally gives up and abandones passenger in construction zone. \
**Country**: USA.\   
**Date**: 14 February, 2026.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/Cyber_Trailer/status/2022365187555352942)  \
**Contributor**: No Safe Words.

### Waymo making dangerous left turn.

**Event**: a Waymo robotaxi in Phoenix slowly inches into an eight-lane intersection for an unprotected left turn, narrowly avoiding a T-bone collision with an oncoming truck, as evidenced by passengers' panicked screams in the 60-second video. \
**Country**: USA.\   
**Date**: 07 March, 2026.\
**Outcome**: near miss.\
[**Video link: X post**](https://x.com/Cyber_Trailer/status/2030702952634290680)\
**Contributor**: No Safe Words.

### Tesla FSD with dirty cameras.

**Event**: The post highlights a critical vulnerability in Tesla’s camera-dependent Full Self-Driving system. The images show the rear and side cameras heavily coated in mud and dirt after just three hours of driving on northern Sweden’s gravel roads in winter. \
**Country**: Sweden.\   
**Date**: Unknown.\
**Outcome**: Risky.\
[**Video link: X post**](https://x.com/NicklasNilsso14/status/2034561242430369916)\
**Contributor**: NicklasNilsso14.

### Tesla FSD navigates through a construction site.

**Event**: A short video clip shared by @ray4tesla
 on March 19, 2026, shows Tesla FSD v14.2.2.5 briefly coming to a full stop in a construction zone (possibly due to a mobile flashing yellow light, worker posture suggesting intent to step out, a visible stop sign, oncoming traffic/pickup truck, or over-sensitivity to potential jaywalkers/pedestrians).The system then correctly recognizes and obeys the construction worker's clear hand signal to proceed, moving forward smoothly. \
**Country**: USA.\   
**Date**: Unknown.\
**Outcome**: Risky.\
[**Video link: X post**](https://x.com/ray4tesla/status/2034669620570038443)\
**Contributor**: ray4tesla.


### Tesla FSD sees merging lane construction sign.

**Event**: The post showcases Tesla's Full Self-Driving (FSD) software version 14.x detecting a construction merge sign on a snowy highway and executing a smooth left lane shift, as captured in a 29-second dashcam video from a Model 3. \
**Country**: USA.\   
**Date**: Unknown.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/mikepat711/status/2034366541320298543)\
**Contributor**: mikepat711.

### Tesla FSD predicts a pedestrain crossing.

**Event**: The post showcases Tesla's Full Self-Driving (FSD) software detecting a pedestrian entering a crosswalk from over 100 meters away in Quzhou, China, slowing the vehicle from 43 km/h to a near-stop over 11 seconds. \
**Country**: China.\   
**Date**: 17 March 2026.\
**Outcome**: Safe.\
[**Video link: X post**](https://x.com/TeslaAaronL/status/2034239644733501655)\
**Contributor**: TeslaAaronL.

### Tesla FSD detects a wheelchair user in the pouring rain.

**Event**: Tesla's Full Self-Driving (FSD) software detected a wheelchair user crossing a Vancouver street in heavy rain at night, slowing the vehicle at a green light despite the driver's initial oversight due to low visibility, highlighting AI's superior perception in adverse conditions. \
**Country**: Canada.\   
**Date**: Unknown.\
**Outcome**: Impressive.\
[**Video link: X post**](https://x.com/DevinOlsenn/status/2034160749820448925)\
**Contributor**: DevinOlsenn.

### Tesla FSD safely interacts with a semi-truck.

**Event**: Tesla's FSD system detects the semi-truck's left signal via cameras, slows by 6 mph to yield space, then accelerates past when the truck shifts right, demonstrating predictive intent recognition in under a second. \
**Country**: USA.\   
**Date**: Unknown.\
**Outcome**: Impressive.\
[**Video link: X post**](https://x.com/mikepat711/status/2034404819792736647)\
**Contributor**: mikepat711.

### Tesla FSD safely interacts with an oversized load.

**Event**: Tesla's FSD V14.2.2.5 demonstrates advanced highway judgment by trailing a swaying oversized load for over a minute, then accelerating 10+ mph to pass only when shoulder barriers cleared. \
**Country**: USA.\   
**Date**: Unknown.\
**Outcome**: Impressive.\
[**Video link: X post**](https://x.com/mikepat711/status/2033607930528907600)\
**Contributor**: mikepat711.


### Waymo Robotaxi vs. Garbage Truck: The Santa Monica Standoff.

**Event**: The post captures an incident in Santa Monica where a Waymo robotaxi halts on a narrow, curved street behind a maneuvering garbage truck, blocking traffic for over 30 seconds as shown in the video, highlighting the vehicle's inability to navigate tight urban spaces without intervention. \
**Country**: USA.\   
**Date**: 9 March 2026.\
**Outcome**: Embarrassing.\
[**Video link: X post**](https://x.com/Cyber_Trailer/status/2031254035106611624)\
**Contributor**: Cyber_Trailer.



**Disclaimer** All events, media, and related materials on this platform are either voluntarily contributed by users or collected from publicly available online sources for archival and informational purposes only. Copyright and all other rights remain with the original creators or respective rights holders.

If you are the owner of any material featured on this platform and do not wish it to be included, please contact me by email and it will be removed promptly.
